version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: wccms-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: wccms
    ports:
      - '5432:5432'
    volumes:
      - wccms-postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: wccms-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cuap.ac.in
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - '5050:80'
    depends_on:
      - database

volumes:
  wccms-postgres-data:
